import "./globals.css";
import type { Metadata } from "next";
import { Inter, Marmelad } from "next/font/google";

import Header from "@/components/Header";

const inter = Inter({ subsets: ["cyrillic", "latin"] });
const marmelad = Marmelad({
  subsets: ["cyrillic", "latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${marmelad.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
